# Generated by Django 4.2 on 2023-04-20 13:56

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_fname_remove_user_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='allow_news',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='only_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pref_cat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pref_price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ver_num',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked', to='api.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='ship_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_shipping', to='api.shipping'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_comments', to='api.product'),
        ),
        migrations.AlterField(
            model_name='history',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='api.product'),
        ),
        migrations.AlterField(
            model_name='history',
            name='ship_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_history', to='api.shipping'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactured_categories', to='api.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='ManufacturerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('descr', models.CharField(max_length=255)),
                ('card_num', models.CharField(blank=True, default='0000-0000-0000-0000', max_length=255)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('ver_num', models.CharField(blank=True, default='000', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_news', models.BooleanField(blank=True, default=True)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('card_num', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('ver_num', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_news', models.BooleanField(blank=True, default=True)),
                ('pref_price', models.FloatField(blank=True, null=True)),
                ('only_available', models.BooleanField(blank=True, null=True)),
                ('pref_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefered_user', to='api.category')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.customeruser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='api.customeruser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='mfr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manufactured_products', to='api.manufactureruser'),
            preserve_default=False,
        ),
    ]
