# Generated by Django 4.2 on 2023-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_comment_dislikes_remove_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
