# Generated by Django 4.2 on 2023-04-17 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descr', models.TextField()),
                ('descr_short', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('manufacturer', models.IntegerField()),
                ('images', models.TextField()),
                ('datasheet', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('capacitance', models.FloatField()),
                ('vdc', models.FloatField()),
                ('vac', models.FloatField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('standart', models.CharField(max_length=255)),
                ('current', models.FloatField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Diode',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('color', models.CharField(max_length=255)),
                ('lum', models.FloatField()),
                ('vf', models.FloatField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='IC',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('package', models.CharField(max_length=255)),
                ('tech', models.CharField(max_length=255)),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Inductor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('inductance', models.FloatField()),
                ('tolerance', models.IntegerField()),
                ('current', models.FloatField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('size', models.IntegerField()),
                ('interface', models.CharField(max_length=255)),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('voltage', models.FloatField()),
                ('capacity', models.FloatField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Resistor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('resistance', models.IntegerField()),
                ('power_value', models.FloatField()),
                ('tolerance', models.FloatField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Transistor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('tech', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('voltage', models.FloatField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('length', models.FloatField()),
                ('voltage', models.FloatField()),
                ('package', models.CharField(max_length=255)),
            ],
            bases=('api.product',),
        ),
    ]
