# Generated by Django 4.2 on 2023-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creditcard',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='show_news',
            new_name='allow_news',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='card_num',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prefered_cat',
            new_name='pref_cat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='only_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pref_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ver_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
