# Generated by Django 4.2 on 2023-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
