# Generated by Django 4.2 on 2023-04-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_creditcard_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
