# Generated by Django 4.2 on 2023-04-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_options_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
