# Generated by Django 4.2 on 2023-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_is_customer_remove_user_is_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='customeruser',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='customeruser',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='manufactureruser',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='pref_price',
        ),
        migrations.AddField(
            model_name='manufactureruser',
            name='email',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufactureruser',
            name='password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='allow_news',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='card_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='descr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='ver_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
