# Generated by Django 4.2 on 2023-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureruser',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
