# Generated by Django 4.2 on 2023-04-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_manufactureruser_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufactureruser',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
