# Generated by Django 4.2 on 2023-04-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_comment_date_alter_history_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rating', '-price', '-amount']},
        ),
    ]
