# Generated by Django 4.2 on 2023-04-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
