# Generated by Django 4.2 on 2023-04-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_cartitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
